# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='adventure',
            new_name='Adventure',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='art',
            new_name='Art',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='historical',
            new_name='Historical',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='religious',
            new_name='Religious',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='romantic',
            new_name='Romantic',
        ),
    ]
