# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180315_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='Adventure',
            new_name='adventure',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='Art',
            new_name='art',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='Historical',
            new_name='historical',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='Religious',
            new_name='religious',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='Romantic',
            new_name='romantic',
        ),
    ]
