# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180316_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='total',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
