# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rating_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
