# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180316_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='primary',
            field=models.AutoField(default=1, max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rating',
            name='place_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.place'),
        ),
    ]
