# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180319_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='phone',
            field=models.CharField(default='', max_length=11),
        ),
    ]
