# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180319_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='close',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='place',
            name='open',
            field=models.CharField(default='', max_length=11),
        ),
    ]
