# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20180319_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='primary',
            field=models.AutoField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
