# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20180319_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='budget_for',
            field=models.IntegerField(default=300),
        ),
    ]
