# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rating_budget_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
